### ISSUE TITLE
Import Exchange specific functions

### ISSUE THREAD

**Issue by PsCustomObject** [PsCustomObject/IT-ToolBox#2]
Port functions to open remote Exchange connection

**Comment by mmcmd** [comment]
Is this simply a matter of importing the module and connecting exopssession?

**Comment by PsCustomObject** [comment]
@mmcmd Yes and no :-) Issue is more a reminder to myself than a real _issue_ per se, if you know a better tool for such situations I'd be glad to hear about it. 

What I have in mind, but is already developed, is a cmdlet used to connect to on-prem Exchange servers. 

I do also have a 2 for Exchange online, 2 as when MFA is not being used, for example for a service account, it is much easier. When MFA is enforced on the account Exchange Online module needs to be used which presents some challenges/"limitations" of sort related to the added security.

**Comment by mmcmd** [comment]
I'd be glad to help if you've got some issues you'd like resolved - I thought it was simply a matter of checking if the exchangeonline module was installed and simply importing it. If that's the case, I'd be glad to do the work for you.

**Comment by PsCustomObject** [comment]
Thanks I gladly accept help, as I said code is in place already I just need to review/Test it I can easily create a new branch and releae the components for testing and revisin. 

That would be much appreciated @mmcmd! 

Of course if you have any idea or suggestion for further module development feel free to open a new issue!

**Comment by PsCustomObject** [comment]
@mmcmd Exchange connection function has been pushed to branch *Version-2.2.0-Dev* feel free to grab a copy and test this out, I should have some time to do so tomorrow but more testing is always good. 

Work on this branch is not yet done as I'm adding more functions before releasing version 2.2.0.

**Comment by mmcmd** [comment]
Thanks, I'll check it out!
