### ISSUE TITLE
New-StringDecryption: Unable to find type [System.Security.Cryptography.RijndaelManagedTransform]

### ISSUE THREAD

**Issue by beta2k** [PsCustomObject/IT-ToolBox#3]
I have a powershell script in which i use `New-StringDecryption`. I used to execute my script with Powershell 5.1 and everything worked fine. I need some features from Powershell 7 and therefore am executing the script now with Powershell 7. However on the following line in my script I get an error now:
> [SecureString]$password = ConvertTo-SecureString -String (New-StringDecryption -EncryptedString 'XXXX') -AsPlainText -Force

The error points to the following line in `New-StringDecryption`:
> \# Create new decryptor Key and IV
>[System.Security.Cryptography.RijndaelManagedTransform]$objectDecryptor = $encryptionObject.CreateDecryptor()

The error states:
> Unable to find type [System.Security.Cryptography.RijndaelManagedTransform]

What am I doing wrong here?
Thanks for your help.

**Comment by PsCustomObject** [comment]
Hello, you're doing nothing wrong the RijndaelManagedTransform class is only available in _full_ [.Net Framework](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanagedtransform?view=netframework-4.8)

So when running the function within PowerShell 7/Core you will get that error as the class is not available. 

I have plans to rewrite the function compatible with PowerShell 7 but my day job is keeping me busy so still did not have time to look into this. 

While it is not the same, what I can suggest to obfuscate the password in the script is using base64 encoding.

It goes alone this is just obfuscation but better than clear text. 

I'm leaving this open for future reference so that you can be notified once I can finally implement the new version.

**Comment by beta2k** [comment]
Thanks for the quick reply! Much appreciaed. 
So there is no other way to manually load the class in my script?

Actually, I copy & pasted the code of `New-StringDecryption.ps1` into my script. So maybe with a one-liner I could just manually load the missing class?

**Comment by PsCustomObject** [comment]
Anytime :) 

No there is no way as that is not implemented in .Net Core upon which PowerShell 7 is built

**Comment by PsCustomObject** [comment]
While I still did not release this you can use something like this to convert to Base64 strings: 

```
function Convert-StringToBase64
{
<#
    .SYNOPSIS
        Cmdlet will convert an input string to its Base64 equivalent.
    
    .DESCRIPTION
        Cmdlet will convert an input string to its Base64 equivalent.
    
    .PARAMETER StringToConvert
        A string representing the text that will be converted to Base64.
    
    .EXAMPLE
        PS C:\> Format-StringToBase64
#>
    
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]
        $StringToConvert
    )
    
    return ([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($StringToConvert)))
}
```

And this to convert back to string

```
function Convert-Base64ToString
{
    <#
    .SYNOPSIS
        Cmdlet will convert a Base64 encoded string to its Unicode equivalent.
    
    .DESCRIPTION
        Cmdlet will convert a Base64 encoded string to its Unicode equivalent.
    
    .PARAMETER StringToConvert
        A string representing the Base64 encoded string to be converted to Unicode.
    
    .EXAMPLE
        PS C:\> Format-StringToBase64
#>
    
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]
        $StringToConvert
    )
    
    return [System.Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($s))
}
```

Mind this is not encryption and only _obfuscating_ the string converting them to base64 which is easily and quickly reverted.

**Comment by beta2k** [comment]
Thanks again for your help. For now I used the solution suggested in this Stackoverflow comment: https://stackoverflow.com/questions/64391495/powershell-script-unable-to-find-type-system-security-cryptography-rijndaelmanag?noredirect=1#comment113865514_64391495
Hence, I simply removed the type cast and it now works.
